import AuthLayout from "@layouts/auth-guard";

function Home() {
  console.log('Home Page')
  return (
    <AuthLayout>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
      <div  className="bg-red-50">Home Page</div>
    </AuthLayout>
  );
};

export default Home;
